[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-3.0",
    "BSD-3-Clause",
    "Zlib"
]

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "offline compile-time dependency; lack of maintenance isn't an issue" }
]


[licenses.private]
ignore = true

# i dunno what i'm able to do about these
[bans]
multiple-versions = "allow"
[bans.workspace-dependencies]
duplicates = "allow"