[package]
name = "maybe_owned_string"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.214", optional = true }

[features]
default = ["std"]
serde = ["dep:serde"]
std = []
